/**
 * Static mapping of TruColor team names → abbreviations.
 *
 * Pro teams are keyed by UPPERCASE name as it appears on TruColor.
 * NCAA schools are keyed by UPPERCASE university name (may include parenthetical nicknames).
 *
 * When the scraper encounters an unmatched name it logs a warning so the mapping can be added.
 */

export const PRO_TEAM_ABBREVS: Record<string, Record<string, string>> = {
  nba: {
    'ATLANTA HAWKS': 'atl',
    'BOSTON CELTICS': 'bos',
    'BROOKLYN NETS': 'bkn',
    'CHARLOTTE HORNETS': 'cha',
    'CHICAGO BULLS': 'chi',
    'CLEVELAND CAVALIERS': 'cle',
    'DALLAS MAVERICKS': 'dal',
    'DENVER NUGGETS': 'den',
    'DETROIT PISTONS': 'det',
    'GOLDEN STATE WARRIORS': 'gsw',
    'HOUSTON ROCKETS': 'hou',
    'INDIANA PACERS': 'ind',
    'LOS ANGELES CLIPPERS': 'lac',
    'LOS ANGELES LAKERS': 'lal',
    'MEMPHIS GRIZZLIES': 'mem',
    'MIAMI HEAT': 'mia',
    'MILWAUKEE BUCKS': 'mil',
    'MINNESOTA TIMBERWOLVES': 'min',
    'NEW ORLEANS PELICANS': 'nop',
    'NEW YORK KNICKS': 'nyk',
    'OKLAHOMA CITY THUNDER': 'okc',
    'ORLANDO MAGIC': 'orl',
    'PHILADELPHIA 76ERS': 'phi',
    'PHOENIX SUNS': 'phx',
    'PORTLAND TRAIL BLAZERS': 'por',
    'SACRAMENTO KINGS': 'sac',
    'SAN ANTONIO SPURS': 'sas',
    'TORONTO RAPTORS': 'tor',
    'UTAH JAZZ': 'uta',
    'WASHINGTON WIZARDS': 'was',
  },
  nfl: {
    'ARIZONA CARDINALS': 'ari',
    'ATLANTA FALCONS': 'atl',
    'BALTIMORE RAVENS': 'bal',
    'BUFFALO BILLS': 'buf',
    'CAROLINA PANTHERS': 'car',
    'CHICAGO BEARS': 'chi',
    'CINCINNATI BENGALS': 'cin',
    'CLEVELAND BROWNS': 'cle',
    'DALLAS COWBOYS': 'dal',
    'DENVER BRONCOS': 'den',
    'DETROIT LIONS': 'det',
    'GREEN BAY PACKERS': 'gb',
    'HOUSTON TEXANS': 'hou',
    'INDIANAPOLIS COLTS': 'ind',
    'JACKSONVILLE JAGUARS': 'jax',
    'KANSAS CITY CHIEFS': 'kc',
    'LAS VEGAS RAIDERS': 'lv',
    'LOS ANGELES CHARGERS': 'lac',
    'LOS ANGELES RAMS': 'lar',
    'MIAMI DOLPHINS': 'mia',
    'MINNESOTA VIKINGS': 'min',
    'NEW ENGLAND PATRIOTS': 'ne',
    'NEW ORLEANS SAINTS': 'no',
    'NEW YORK GIANTS': 'nyg',
    'NEW YORK JETS': 'nyj',
    'PHILADELPHIA EAGLES': 'phi',
    'PITTSBURGH STEELERS': 'pit',
    'SAN FRANCISCO 49ERS': 'sf',
    'SEATTLE SEAHAWKS': 'sea',
    'TAMPA BAY BUCCANEERS': 'tb',
    'TENNESSEE TITANS': 'ten',
    'WASHINGTON COMMANDERS': 'was',
  },
  nhl: {
    'ANAHEIM DUCKS': 'ana',
    'BOSTON BRUINS': 'bos',
    'BUFFALO SABRES': 'buf',
    'CALGARY FLAMES': 'cgy',
    'CAROLINA HURRICANES': 'car',
    'CHICAGO BLACKHAWKS': 'chi',
    'COLORADO AVALANCHE': 'col',
    'COLUMBUS BLUE JACKETS': 'cbj',
    'DALLAS STARS': 'dal',
    'DETROIT RED WINGS': 'det',
    'EDMONTON OILERS': 'edm',
    'FLORIDA PANTHERS': 'fla',
    'LOS ANGELES KINGS': 'lak',
    'MINNESOTA WILD': 'min',
    'MONTRÉAL CANADIENS': 'mtl',
    'MONTREAL CANADIENS': 'mtl',
    'NASHVILLE PREDATORS': 'nsh',
    'NEW JERSEY DEVILS': 'njd',
    'NEW YORK ISLANDERS': 'nyi',
    'NEW YORK RANGERS': 'nyr',
    'OTTAWA SENATORS': 'ott',
    'PHILADELPHIA FLYERS': 'phi',
    'PITTSBURGH PENGUINS': 'pit',
    'SAN JOSE SHARKS': 'sjs',
    'SEATTLE KRAKEN': 'sea',
    'ST. LOUIS BLUES': 'stl',
    'TAMPA BAY LIGHTNING': 'tbl',
    'TORONTO MAPLE LEAFS': 'tor',
    'UTAH HOCKEY CLUB': 'uta',
    'UTAH MAMMOTH': 'uta',
    'VANCOUVER CANUCKS': 'van',
    'VEGAS GOLDEN KNIGHTS': 'vgk',
    'WASHINGTON CAPITALS': 'wsh',
    'WINNIPEG JETS': 'wpg',
  },
  mlb: {
    'ARIZONA DIAMONDBACKS': 'ari',
    'ATLANTA BRAVES': 'atl',
    'BALTIMORE ORIOLES': 'bal',
    'BOSTON RED SOX': 'bos',
    'CHICAGO CUBS': 'chc',
    'CHICAGO WHITE SOX': 'chw',
    'CINCINNATI REDS': 'cin',
    'CLEVELAND GUARDIANS': 'cle',
    'COLORADO ROCKIES': 'col',
    'DETROIT TIGERS': 'det',
    'HOUSTON ASTROS': 'hou',
    'KANSAS CITY ROYALS': 'kc',
    'LAS VEGAS ATHLETICS': 'oak',
    'LOS ANGELES ANGELS': 'laa',
    'LOS ANGELES DODGERS': 'lad',
    'MIAMI MARLINS': 'mia',
    'MILWAUKEE BREWERS': 'mil',
    'MINNESOTA TWINS': 'min',
    'NEW YORK METS': 'nym',
    'NEW YORK YANKEES': 'nyy',
    'OAKLAND ATHLETICS': 'oak',
    'PHILADELPHIA PHILLIES': 'phi',
    'PITTSBURGH PIRATES': 'pit',
    'SAN DIEGO PADRES': 'sd',
    'SAN FRANCISCO GIANTS': 'sf',
    'SEATTLE MARINERS': 'sea',
    'ST. LOUIS CARDINALS': 'stl',
    'TAMPA BAY RAYS': 'tb',
    'TEXAS RANGERS': 'tex',
    'TORONTO BLUE JAYS': 'tor',
    'WASHINGTON NATIONALS': 'was',
  },
};

/**
 * NCAA D1 school mappings.
 * Key = UPPERCASE school name as it appears on TruColor (may include parenthetical).
 * Value = slug abbreviation.
 *
 * TruColor uses full university names like "UNIVERSITY OF ALABAMA" or
 * "THE UNIVERSITY OF MISSISSIPPI (Ole Miss)". We strip the parenthetical
 * when matching, but include common variants.
 */
export const NCAA_SCHOOL_ABBREVS: Record<string, string> = {
  // SEC
  'UNIVERSITY OF ALABAMA': 'alabama',
  'AUBURN UNIVERSITY': 'auburn',
  'UNIVERSITY OF ARKANSAS': 'arkansas',
  'UNIVERSITY OF FLORIDA': 'florida',
  'UNIVERSITY OF GEORGIA': 'georgia',
  'UNIVERSITY OF KENTUCKY': 'kentucky',
  'LOUISIANA STATE UNIVERSITY': 'lsu',
  'THE UNIVERSITY OF MISSISSIPPI': 'ole-miss',
  'MISSISSIPPI STATE UNIVERSITY': 'miss-st',
  'UNIVERSITY OF MISSOURI': 'missouri',
  'UNIVERSITY OF OKLAHOMA': 'oklahoma',
  'UNIVERSITY OF SOUTH CAROLINA': 'south-carolina',
  'UNIVERSITY OF TENNESSEE': 'tennessee',
  'TEXAS A&M UNIVERSITY': 'texas-am',
  'THE UNIVERSITY OF TEXAS AT AUSTIN': 'texas',
  'UNIVERSITY OF TEXAS AT AUSTIN': 'texas',
  'VANDERBILT UNIVERSITY': 'vanderbilt',
  // ACC
  'BOSTON COLLEGE': 'boston-college',
  'CALIFORNIA POLYTECHNIC STATE UNIVERSITY': 'cal-poly',
  'CLEMSON UNIVERSITY': 'clemson',
  'DUKE UNIVERSITY': 'duke',
  'FLORIDA STATE UNIVERSITY': 'florida-st',
  'GEORGIA INSTITUTE OF TECHNOLOGY': 'georgia-tech',
  'UNIVERSITY OF LOUISVILLE': 'louisville',
  'UNIVERSITY OF MIAMI': 'miami',
  'UNIVERSITY OF NORTH CAROLINA AT CHAPEL HILL': 'unc',
  'NORTH CAROLINA STATE UNIVERSITY': 'nc-state',
  'UNIVERSITY OF NOTRE DAME': 'notre-dame',
  'UNIVERSITY OF PITTSBURGH': 'pittsburgh',
  'SOUTHERN METHODIST UNIVERSITY': 'smu',
  'STANFORD UNIVERSITY': 'stanford',
  'SYRACUSE UNIVERSITY': 'syracuse',
  'UNIVERSITY OF CALIFORNIA, BERKELEY': 'cal',
  'UNIVERSITY OF VIRGINIA': 'virginia',
  'VIRGINIA POLYTECHNIC INSTITUTE AND STATE UNIVERSITY': 'virginia-tech',
  'WAKE FOREST UNIVERSITY': 'wake-forest',
  // Big Ten
  'UNIVERSITY OF ILLINOIS AT URBANA-CHAMPAIGN': 'illinois',
  'UNIVERSITY OF ILLINOIS AT URBANA–CHAMPAIGN': 'illinois',
  'INDIANA UNIVERSITY': 'indiana',
  'UNIVERSITY OF IOWA': 'iowa',
  'UNIVERSITY OF MARYLAND': 'maryland',
  'UNIVERSITY OF MICHIGAN': 'michigan',
  'MICHIGAN STATE UNIVERSITY': 'michigan-st',
  'UNIVERSITY OF MINNESOTA': 'minnesota',
  'UNIVERSITY OF NEBRASKA': 'nebraska',
  'UNIVERSITY OF NEBRASKA–LINCOLN': 'nebraska',
  'NORTHWESTERN UNIVERSITY': 'northwestern',
  'THE OHIO STATE UNIVERSITY': 'ohio-st',
  'OHIO STATE UNIVERSITY': 'ohio-st',
  'OREGON STATE UNIVERSITY': 'oregon-st',
  'THE PENNSYLVANIA STATE UNIVERSITY': 'penn-st',
  'PENNSYLVANIA STATE UNIVERSITY': 'penn-st',
  'PURDUE UNIVERSITY': 'purdue',
  'RUTGERS, THE STATE UNIVERSITY OF NEW JERSEY': 'rutgers',
  'RUTGERS UNIVERSITY': 'rutgers',
  'UNIVERSITY OF CALIFORNIA, LOS ANGELES': 'ucla',
  'UNIVERSITY OF OREGON': 'oregon',
  'UNIVERSITY OF SOUTHERN CALIFORNIA': 'usc',
  'UNIVERSITY OF WASHINGTON': 'washington',
  'UNIVERSITY OF WISCONSIN': 'wisconsin',
  'UNIVERSITY OF WISCONSIN–MADISON': 'wisconsin',
  // Big 12
  'ARIZONA STATE UNIVERSITY': 'arizona-st',
  'BAYLOR UNIVERSITY': 'baylor',
  'BRIGHAM YOUNG UNIVERSITY': 'byu',
  'UNIVERSITY OF ARIZONA': 'arizona',
  'UNIVERSITY OF CENTRAL FLORIDA': 'ucf',
  'UNIVERSITY OF CINCINNATI': 'cincinnati',
  'UNIVERSITY OF COLORADO': 'colorado',
  'UNIVERSITY OF COLORADO BOULDER': 'colorado',
  'UNIVERSITY OF HOUSTON': 'houston',
  'IOWA STATE UNIVERSITY': 'iowa-st',
  'UNIVERSITY OF KANSAS': 'kansas',
  'KANSAS STATE UNIVERSITY': 'kansas-st',
  'OKLAHOMA STATE UNIVERSITY': 'oklahoma-st',
  'TEXAS CHRISTIAN UNIVERSITY': 'tcu',
  'TEXAS TECH UNIVERSITY': 'texas-tech',
  'UNIVERSITY OF UTAH': 'utah',
  'WEST VIRGINIA UNIVERSITY': 'west-virginia',
  // Big East
  'BUTLER UNIVERSITY': 'butler',
  'UNIVERSITY OF CONNECTICUT': 'uconn',
  'CREIGHTON UNIVERSITY': 'creighton',
  'DEPAUL UNIVERSITY': 'depaul',
  'GEORGETOWN UNIVERSITY': 'georgetown',
  'MARQUETTE UNIVERSITY': 'marquette',
  'PROVIDENCE COLLEGE': 'providence',
  'SETON HALL UNIVERSITY': 'seton-hall',
  'ST. JOHN\'S UNIVERSITY': 'st-johns',
  'VILLANOVA UNIVERSITY': 'villanova',
  'XAVIER UNIVERSITY': 'xavier',
  // AAC (American Athletic Conference)
  'EAST CAROLINA UNIVERSITY': 'east-carolina',
  'FLORIDA ATLANTIC UNIVERSITY': 'fau',
  'UNIVERSITY OF MEMPHIS': 'memphis',
  'UNIVERSITY OF NORTH TEXAS': 'north-texas',
  'RICE UNIVERSITY': 'rice',
  'UNIVERSITY OF SOUTH FLORIDA': 'usf',
  'TEMPLE UNIVERSITY': 'temple',
  'TULANE UNIVERSITY': 'tulane',
  'THE UNIVERSITY OF TULSA': 'tulsa',
  'UNIVERSITY OF TULSA': 'tulsa',
  'UNITED STATES MILITARY ACADEMY': 'army',
  'UNITED STATES NAVAL ACADEMY': 'navy',
  'UNIVERSITY OF ALABAMA AT BIRMINGHAM': 'uab',
  'CHARLOTTE': 'charlotte',
  'UNIVERSITY OF NORTH CAROLINA AT CHARLOTTE': 'charlotte',
  'WICHITA STATE UNIVERSITY': 'wichita-st',
  // Pac-12 (remaining members)
  'BOISE STATE UNIVERSITY': 'boise-st',
  'COLORADO STATE UNIVERSITY': 'colorado-st',
  'FRESNO STATE': 'fresno-st',
  'CALIFORNIA STATE UNIVERSITY, FRESNO': 'fresno-st',
  'SAN DIEGO STATE UNIVERSITY': 'san-diego-st',
  'UNIVERSITY OF NEVADA, LAS VEGAS': 'unlv',
  // Mountain West
  'AIR FORCE ACADEMY': 'air-force',
  'UNITED STATES AIR FORCE ACADEMY': 'air-force',
  'UNIVERSITY OF HAWAII': 'hawaii',
  "UNIVERSITY OF HAWAI'I AT MĀNOA": 'hawaii',
  'UNIVERSITY OF NEW MEXICO': 'new-mexico',
  'NEW MEXICO STATE UNIVERSITY': 'new-mexico-st',
  'UNIVERSITY OF NEVADA': 'nevada',
  'UNIVERSITY OF NEVADA, RENO': 'nevada',
  'SAN JOSÉ STATE UNIVERSITY': 'san-jose-st',
  'SAN JOSE STATE UNIVERSITY': 'san-jose-st',
  'UTAH STATE UNIVERSITY': 'utah-st',
  'UNIVERSITY OF WYOMING': 'wyoming',
  // Sun Belt
  'APPALACHIAN STATE UNIVERSITY': 'appalachian-st',
  'UNIVERSITY OF ARKANSAS AT LITTLE ROCK': 'little-rock',
  'ARKANSAS STATE UNIVERSITY': 'arkansas-st',
  'COASTAL CAROLINA UNIVERSITY': 'coastal-carolina',
  'GEORGIA SOUTHERN UNIVERSITY': 'georgia-southern',
  'GEORGIA STATE UNIVERSITY': 'georgia-st',
  'JAMES MADISON UNIVERSITY': 'james-madison',
  'UNIVERSITY OF LOUISIANA AT LAFAYETTE': 'louisiana',
  'LOUISIANA-LAFAYETTE': 'louisiana',
  'UNIVERSITY OF LOUISIANA AT MONROE': 'louisiana-monroe',
  'MARSHALL UNIVERSITY': 'marshall',
  'OLD DOMINION UNIVERSITY': 'old-dominion',
  'UNIVERSITY OF SOUTH ALABAMA': 'south-alabama',
  'SOUTHERN MISSISSIPPI': 'southern-miss',
  'THE UNIVERSITY OF SOUTHERN MISSISSIPPI': 'southern-miss',
  'UNIVERSITY OF SOUTHERN MISSISSIPPI': 'southern-miss',
  'TEXAS STATE UNIVERSITY': 'texas-st',
  'TROY UNIVERSITY': 'troy',
  // Conference USA
  'FLORIDA INTERNATIONAL UNIVERSITY': 'fiu',
  'JACKSONVILLE STATE UNIVERSITY': 'jacksonville-st',
  'KENNESAW STATE UNIVERSITY': 'kennesaw-st',
  'LIBERTY UNIVERSITY': 'liberty',
  'LOUISIANA TECH UNIVERSITY': 'louisiana-tech',
  'MIDDLE TENNESSEE STATE UNIVERSITY': 'middle-tenn',
  'SAM HOUSTON STATE UNIVERSITY': 'sam-houston',
  'UNIVERSITY OF TEXAS AT EL PASO': 'utep',
  'UNIVERSITY OF TEXAS AT SAN ANTONIO': 'utsa',
  'WESTERN KENTUCKY UNIVERSITY': 'wku',
  // Mid-American Conference (MAC)
  'UNIVERSITY OF AKRON': 'akron',
  'BALL STATE UNIVERSITY': 'ball-st',
  'BOWLING GREEN STATE UNIVERSITY': 'bowling-green',
  'UNIVERSITY AT BUFFALO': 'buffalo',
  'CENTRAL MICHIGAN UNIVERSITY': 'central-michigan',
  'EASTERN MICHIGAN UNIVERSITY': 'eastern-michigan',
  'KENT STATE UNIVERSITY': 'kent-st',
  'MIAMI UNIVERSITY': 'miami-oh',
  'NORTHERN ILLINOIS UNIVERSITY': 'northern-illinois',
  'OHIO UNIVERSITY': 'ohio',
  'UNIVERSITY OF TOLEDO': 'toledo',
  'WESTERN MICHIGAN UNIVERSITY': 'western-michigan',
  // Ivy League
  'BROWN UNIVERSITY': 'brown',
  'COLUMBIA UNIVERSITY': 'columbia',
  'CORNELL UNIVERSITY': 'cornell',
  'DARTMOUTH COLLEGE': 'dartmouth',
  'HARVARD UNIVERSITY': 'harvard',
  'UNIVERSITY OF PENNSYLVANIA': 'penn',
  'PRINCETON UNIVERSITY': 'princeton',
  'YALE UNIVERSITY': 'yale',
  // America East
  'UNIVERSITY OF ALBANY': 'albany',
  'STATE UNIVERSITY OF NEW YORK AT ALBANY': 'albany',
  'BINGHAMTON UNIVERSITY': 'binghamton',
  'UNIVERSITY OF MAINE': 'maine',
  'UNIVERSITY OF MARYLAND, BALTIMORE COUNTY': 'umbc',
  'UNIVERSITY OF NEW HAMPSHIRE': 'new-hampshire',
  'NEW JERSEY INSTITUTE OF TECHNOLOGY': 'njit',
  'STATE UNIVERSITY OF NEW YORK AT STONY BROOK': 'stony-brook',
  'STONY BROOK UNIVERSITY': 'stony-brook',
  'UNIVERSITY OF VERMONT': 'vermont',
  'BRYANT UNIVERSITY': 'bryant',
  // Atlantic 10
  'DAVIDSON COLLEGE': 'davidson',
  'DUQUESNE UNIVERSITY': 'duquesne',
  'FORDHAM UNIVERSITY': 'fordham',
  'GEORGE MASON UNIVERSITY': 'george-mason',
  'GEORGE WASHINGTON UNIVERSITY': 'george-washington',
  'THE GEORGE WASHINGTON UNIVERSITY': 'george-washington',
  'LA SALLE UNIVERSITY': 'la-salle',
  'LOYOLA UNIVERSITY CHICAGO': 'loyola-chicago',
  'UNIVERSITY OF MASSACHUSETTS': 'umass',
  'UNIVERSITY OF MASSACHUSETTS AMHERST': 'umass',
  'UNIVERSITY OF RICHMOND': 'richmond',
  'SAINT BONAVENTURE UNIVERSITY': 'st-bonaventure',
  "SAINT JOSEPH'S UNIVERSITY": 'saint-josephs',
  'SAINT LOUIS UNIVERSITY': 'saint-louis',
  'VIRGINIA COMMONWEALTH UNIVERSITY': 'vcu',
  'UNIVERSITY OF DAYTON': 'dayton',
  // Atlantic Sun (ASUN)
  'BELLARMINE UNIVERSITY': 'bellarmine',
  'CENTRAL ARKANSAS': 'central-arkansas',
  'UNIVERSITY OF CENTRAL ARKANSAS': 'central-arkansas',
  'EASTERN KENTUCKY UNIVERSITY': 'eastern-kentucky',
  'FLORIDA GULF COAST UNIVERSITY': 'fgcu',
  'UNIVERSITY OF NORTH FLORIDA': 'north-florida',
  'LIPSCOMB UNIVERSITY': 'lipscomb',
  'QUEENS UNIVERSITY OF CHARLOTTE': 'queens',
  'STETSON UNIVERSITY': 'stetson',
  'UNIVERSITY OF NORTH ALABAMA': 'north-alabama',
  // Big Sky
  'EASTERN WASHINGTON UNIVERSITY': 'eastern-washington',
  'UNIVERSITY OF IDAHO': 'idaho',
  'IDAHO STATE UNIVERSITY': 'idaho-st',
  'UNIVERSITY OF MONTANA': 'montana',
  'MONTANA STATE UNIVERSITY': 'montana-st',
  'UNIVERSITY OF NORTHERN COLORADO': 'northern-colorado',
  'NORTHERN ARIZONA UNIVERSITY': 'northern-arizona',
  'PORTLAND STATE UNIVERSITY': 'portland-st',
  'SACRAMENTO STATE': 'sacramento-st',
  'CALIFORNIA STATE UNIVERSITY, SACRAMENTO': 'sacramento-st',
  'WEBER STATE UNIVERSITY': 'weber-st',
  // Big South
  'CHARLESTON SOUTHERN UNIVERSITY': 'charleston-southern',
  'GARDNER-WEBB UNIVERSITY': 'gardner-webb',
  'HIGH POINT UNIVERSITY': 'high-point',
  'LONGWOOD UNIVERSITY': 'longwood',
  'PRESBYTERIAN COLLEGE': 'presbyterian',
  'RADFORD UNIVERSITY': 'radford',
  'UNIVERSITY OF NORTH CAROLINA AT ASHEVILLE': 'unc-asheville',
  'UNIVERSITY OF SOUTH CAROLINA UPSTATE': 'sc-upstate',
  'WINTHROP UNIVERSITY': 'winthrop',
  // Big West
  'CALIFORNIA STATE UNIVERSITY, BAKERSFIELD': 'cal-st-bakersfield',
  'CALIFORNIA STATE UNIVERSITY, FULLERTON': 'cal-st-fullerton',
  'CALIFORNIA STATE UNIVERSITY, LONG BEACH': 'long-beach-st',
  'CALIFORNIA STATE UNIVERSITY, NORTHRIDGE': 'cal-st-northridge',
  'UNIVERSITY OF CALIFORNIA, DAVIS': 'uc-davis',
  'UNIVERSITY OF CALIFORNIA, IRVINE': 'uc-irvine',
  'UNIVERSITY OF CALIFORNIA, RIVERSIDE': 'uc-riverside',
  'UNIVERSITY OF CALIFORNIA, SAN DIEGO': 'uc-san-diego',
  'UNIVERSITY OF CALIFORNIA, SANTA BARBARA': 'uc-santa-barbara',
  // CAA (Coastal Athletic Association)
  'COLLEGE OF CHARLESTON': 'charleston',
  'UNIVERSITY OF DELAWARE': 'delaware',
  'DREXEL UNIVERSITY': 'drexel',
  'ELON UNIVERSITY': 'elon',
  'HAMPTON UNIVERSITY': 'hampton',
  'HOFSTRA UNIVERSITY': 'hofstra',
  'MONMOUTH UNIVERSITY': 'monmouth',
  'NORTHEASTERN UNIVERSITY': 'northeastern',
  'TOWSON UNIVERSITY': 'towson',
  'COLLEGE OF WILLIAM & MARY': 'william-mary',
  'UNIVERSITY OF NORTH CAROLINA AT WILMINGTON': 'unc-wilmington',
  // Horizon League
  'CLEVELAND STATE UNIVERSITY': 'cleveland-st',
  'UNIVERSITY OF DETROIT MERCY': 'detroit-mercy',
  'UNIVERSITY OF WISCONSIN–GREEN BAY': 'green-bay',
  'UNIVERSITY OF WISCONSIN-GREEN BAY': 'green-bay',
  'UNIVERSITY OF WISCONSIN-MILWAUKEE': 'milwaukee',
  'UNIVERSITY OF WISCONSIN–MILWAUKEE': 'milwaukee',
  'NORTHERN KENTUCKY UNIVERSITY': 'northern-kentucky',
  'OAKLAND UNIVERSITY': 'oakland',
  'PURDUE UNIVERSITY FORT WAYNE': 'purdue-fort-wayne',
  'ROBERT MORRIS UNIVERSITY': 'robert-morris',
  'WRIGHT STATE UNIVERSITY': 'wright-st',
  'YOUNGSTOWN STATE UNIVERSITY': 'youngstown-st',
  // MAAC (Metro Atlantic Athletic)
  'CANISIUS COLLEGE': 'canisius',
  'FAIRFIELD UNIVERSITY': 'fairfield',
  'IONA UNIVERSITY': 'iona',
  'MANHATTAN COLLEGE': 'manhattan',
  'MARIST COLLEGE': 'marist',
  'MOUNT ST. MARY\'S UNIVERSITY': 'mount-st-marys',
  'NIAGARA UNIVERSITY': 'niagara',
  'QUINNIPIAC UNIVERSITY': 'quinnipiac',
  'RIDER UNIVERSITY': 'rider',
  'SACRED HEART UNIVERSITY': 'sacred-heart',
  'SAINT PETER\'S UNIVERSITY': 'saint-peters',
  'SIENA COLLEGE': 'siena',
  // MEAC (Mid-Eastern Athletic)
  'BETHUNE-COOKMAN UNIVERSITY': 'bethune-cookman',
  'COPPIN STATE UNIVERSITY': 'coppin-st',
  'DELAWARE STATE UNIVERSITY': 'delaware-st',
  'HOWARD UNIVERSITY': 'howard',
  'UNIVERSITY OF MARYLAND EASTERN SHORE': 'maryland-es',
  'MORGAN STATE UNIVERSITY': 'morgan-st',
  'NORFOLK STATE UNIVERSITY': 'norfolk-st',
  'NORTH CAROLINA CENTRAL UNIVERSITY': 'nc-central',
  'SOUTH CAROLINA STATE UNIVERSITY': 'sc-state',
  // Missouri Valley
  'BELMONT UNIVERSITY': 'belmont',
  'BRADLEY UNIVERSITY': 'bradley',
  'DRAKE UNIVERSITY': 'drake',
  'UNIVERSITY OF EVANSVILLE': 'evansville',
  'ILLINOIS STATE UNIVERSITY': 'illinois-st',
  'INDIANA STATE UNIVERSITY': 'indiana-st',
  'MISSOURI STATE UNIVERSITY': 'missouri-st',
  'MURRAY STATE UNIVERSITY': 'murray-st',
  'UNIVERSITY OF NORTHERN IOWA': 'northern-iowa',
  'SOUTHERN ILLINOIS UNIVERSITY': 'southern-illinois',
  'UNIVERSITY OF ILLINOIS SPRINGFIELD': 'uis',
  'VALPARAISO UNIVERSITY': 'valparaiso',
  // Northeast Conference
  'CENTRAL CONNECTICUT STATE UNIVERSITY': 'central-conn',
  'FAIRLEIGH DICKINSON UNIVERSITY': 'fairleigh-dickinson',
  'LE MOYNE COLLEGE': 'le-moyne',
  'LONG ISLAND UNIVERSITY': 'liu',
  'MERRIMACK COLLEGE': 'merrimack',
  'SAINT FRANCIS UNIVERSITY': 'saint-francis-pa',
  'STONEHILL COLLEGE': 'stonehill',
  'WAGNER COLLEGE': 'wagner',
  // Ohio Valley
  'EASTERN ILLINOIS UNIVERSITY': 'eastern-illinois',
  'LINDENWOOD UNIVERSITY': 'lindenwood',
  'LITTLE ROCK': 'little-rock',
  'MOREHEAD STATE UNIVERSITY': 'morehead-st',
  'SOUTHEAST MISSOURI STATE UNIVERSITY': 'se-missouri-st',
  'SOUTHERN INDIANA UNIVERSITY': 'southern-indiana',
  'UNIVERSITY OF SOUTHERN INDIANA': 'southern-indiana',
  'TENNESSEE STATE UNIVERSITY': 'tennessee-st',
  'TENNESSEE TECHNOLOGICAL UNIVERSITY': 'tennessee-tech',
  'UNIVERSITY OF TENNESSEE AT MARTIN': 'ut-martin',
  'WESTERN ILLINOIS UNIVERSITY': 'western-illinois',
  // Patriot League
  'AMERICAN UNIVERSITY': 'american',
  'BOSTON UNIVERSITY': 'boston-u',
  'BUCKNELL UNIVERSITY': 'bucknell',
  'COLGATE UNIVERSITY': 'colgate',
  'COLLEGE OF THE HOLY CROSS': 'holy-cross',
  'LAFAYETTE COLLEGE': 'lafayette',
  'LEHIGH UNIVERSITY': 'lehigh',
  'LOYOLA UNIVERSITY MARYLAND': 'loyola-md',
  // Southern Conference
  'THE CITADEL': 'citadel',
  'EAST TENNESSEE STATE UNIVERSITY': 'etsu',
  'FURMAN UNIVERSITY': 'furman',
  'MERCER UNIVERSITY': 'mercer',
  'UNIVERSITY OF NORTH CAROLINA AT GREENSBORO': 'unc-greensboro',
  'SAMFORD UNIVERSITY': 'samford',
  'UNIVERSITY OF TENNESSEE AT CHATTANOOGA': 'chattanooga',
  'VIRGINIA MILITARY INSTITUTE': 'vmi',
  'WESTERN CAROLINA UNIVERSITY': 'western-carolina',
  'WOFFORD COLLEGE': 'wofford',
  // Southland Conference
  'HOUSTON CHRISTIAN UNIVERSITY': 'houston-christian',
  'INCARNATE WORD': 'incarnate-word',
  'UNIVERSITY OF THE INCARNATE WORD': 'incarnate-word',
  'LAMAR UNIVERSITY': 'lamar',
  'MCNEESE STATE UNIVERSITY': 'mcneese',
  'NICHOLLS STATE UNIVERSITY': 'nicholls',
  'NORTHWESTERN STATE UNIVERSITY': 'northwestern-st',
  'SOUTHEASTERN LOUISIANA UNIVERSITY': 'se-louisiana',
  'STEPHEN F. AUSTIN STATE UNIVERSITY': 'sfa',
  'TEXAS A&M UNIVERSITY-CORPUS CHRISTI': 'tamucc',
  'TEXAS A&M UNIVERSITY–CORPUS CHRISTI': 'tamucc',
  // SWAC (Southwestern Athletic)
  'ALABAMA A&M UNIVERSITY': 'alabama-am',
  'ALABAMA STATE UNIVERSITY': 'alabama-st',
  'ALCORN STATE UNIVERSITY': 'alcorn-st',
  'ARKANSAS-PINE BLUFF': 'arkansas-pb',
  'UNIVERSITY OF ARKANSAS AT PINE BLUFF': 'arkansas-pb',
  'GRAMBLING STATE UNIVERSITY': 'grambling',
  'JACKSON STATE UNIVERSITY': 'jackson-st',
  'MISSISSIPPI VALLEY STATE UNIVERSITY': 'mvsu',
  'PRAIRIE VIEW A&M UNIVERSITY': 'prairie-view',
  'SOUTHERN UNIVERSITY': 'southern',
  'TEXAS SOUTHERN UNIVERSITY': 'texas-southern',
  // Summit League
  'UNIVERSITY OF DENVER': 'denver',
  'KANSAS CITY': 'kansas-city',
  'UNIVERSITY OF MISSOURI-KANSAS CITY': 'kansas-city',
  'UNIVERSITY OF NEBRASKA OMAHA': 'omaha',
  'NORTH DAKOTA STATE UNIVERSITY': 'north-dakota-st',
  'UNIVERSITY OF NORTH DAKOTA': 'north-dakota',
  'ORAL ROBERTS UNIVERSITY': 'oral-roberts',
  'UNIVERSITY OF SOUTH DAKOTA': 'south-dakota',
  'SOUTH DAKOTA STATE UNIVERSITY': 'south-dakota-st',
  'ST. THOMAS': 'st-thomas',
  'UNIVERSITY OF ST. THOMAS': 'st-thomas',
  // West Coast Conference
  'UNIVERSITY OF THE PACIFIC': 'pacific',
  'GONZAGA UNIVERSITY': 'gonzaga',
  'LOYOLA MARYMOUNT UNIVERSITY': 'loyola-marymount',
  'PEPPERDINE UNIVERSITY': 'pepperdine',
  'UNIVERSITY OF PORTLAND': 'portland',
  'SAINT MARY\'S COLLEGE OF CALIFORNIA': 'saint-marys',
  'UNIVERSITY OF SAN DIEGO': 'san-diego',
  'UNIVERSITY OF SAN FRANCISCO': 'san-francisco',
  'SANTA CLARA UNIVERSITY': 'santa-clara',
  // WAC (Western Athletic)
  'ABILENE CHRISTIAN UNIVERSITY': 'abilene-christian',
  'CALIFORNIA BAPTIST UNIVERSITY': 'cal-baptist',
  'GRAND CANYON UNIVERSITY': 'grand-canyon',
  'SEATTLE UNIVERSITY': 'seattle',
  'STEPHEN F. AUSTIN': 'sfa',
  'TARLETON STATE UNIVERSITY': 'tarleton-st',
  'UNIVERSITY OF TEXAS RIO GRANDE VALLEY': 'utrgv',
  'UTAH VALLEY UNIVERSITY': 'utah-valley',
  // Independents & misc
  'NORTH CAROLINA A&T STATE UNIVERSITY': 'nc-at',
  'FLORIDA A&M UNIVERSITY': 'florida-am',

  // ── Alternate formal names as they appear on TruColor ──
  // (longer official names with location suffixes, "THE" prefix, etc.)
  'THE UNIVERSITY OF ALABAMA': 'alabama',
  'THE UNIVERSITY OF ARIZONA': 'arizona',
  'THE UNIVERSITY OF IOWA': 'iowa',
  'THE UNIVERSITY OF KANSAS': 'kansas',
  'THE UNIVERSITY OF NORTH CAROLINA AT CHAPEL HILL': 'unc',
  'THE UNIVERSITY OF NORTH CAROLINA AT CHARLOTTE': 'charlotte',
  'THE UNIVERSITY OF NORTH CAROLINA AT GREENSBORO': 'unc-greensboro',
  'THE UNIVERSITY OF NORTH CAROLINA AT WILMINGTON': 'unc-wilmington',
  'THE UNIVERSITY OF TENNESSEE AT CHATTANOOGA': 'chattanooga',
  'THE UNIVERSITY OF TENNESSEE AT KNOXVILLE': 'tennessee',
  'THE UNIVERSITY OF TENNESSEE AT MARTIN': 'ut-martin',
  'THE UNIVERSITY OF TEXAS AT ARLINGTON': 'uta-arlington',
  'THE UNIVERSITY OF TEXAS AT EL PASO': 'utep',
  'THE UNIVERSITY OF TEXAS AT SAN ANTONIO': 'utsa',
  'THE UNIVERSITY OF TOLEDO': 'toledo',
  'THE UNIVERSITY OF AKRON': 'akron',
  'THE OHIO STATE UNIVERSITY AT COLUMBUS': 'ohio-st',
  'THE CITADEL, THE MILITARY COLLEGE OF SOUTH CAROLINA': 'citadel',
  'ALABAMA AGRICULTURAL AND MECHANICAL UNIVERSITY': 'alabama-am',
  'FLORIDA AGRICULTURAL AND MECHANICAL UNIVERSITY': 'florida-am',
  'LOUISIANA STATE UNIVERSITY AND AGRICULTURAL AND MECHANICAL COLLEGE': 'lsu',
  'SOUTHERN UNIVERSITY AND AGRICULTURAL AND MECHANICAL COLLEGE': 'southern',
  'ARKANSAS STATE UNIVERSITY - JONESBORO': 'arkansas-st',
  'BRIGHAM YOUNG UNIVERSITY - PROVO': 'byu',
  'FAIRLEIGH DICKINSON UNIVERSITY, METROPOLITAN CAMPUS': 'fairleigh-dickinson',
  'INDIANA UNIVERSITY BLOOMINGTON': 'indiana',
  'IOWA STATE UNIVERSITY OF SCIENCE AND TECHNOLOGY': 'iowa-st',
  'NORTHWESTERN STATE UNIVERSITY OF LOUISIANA': 'northwestern-st',
  'OKLAHOMA STATE UNIVERSITY, STILLWATER': 'oklahoma-st',
  'PENN STATE UNIVERSITY PARK': 'penn-st',
  'RUTGERS UNIVERSITY - NEW BRUNSWICK': 'rutgers',
  'SOUTHERN ILLINOIS UNIVERSITY CARBONDALE': 'southern-illinois',
  'SOUTHERN ILLINOIS UNIVERSITY EDWARDSVILLE': 'siue',
  'UNIVERSITY OF HAWAII AT MANOA': 'hawaii',
  'UNIVERSITY OF ILLINOIS CHICAGO': 'uic',
  'UNIVERSITY OF ILLINOIS URBANA-CHAMPAIGN': 'illinois',
  'UNIVERSITY OF MARYLAND, COLLEGE PARK': 'maryland',
  'UNIVERSITY OF MINNESOTA, TWIN CITIES CAMPUS': 'minnesota',
  'UNIVERSITY OF NEBRASKA-LINCOLN': 'nebraska',
  'UNIVERSITY OF NORTH CAROLINA ASHEVILLE': 'unc-asheville',
  'UNIVERSITY OF WISCONSIN-MADISON': 'wisconsin',
  'WASHINGTON STATE UNIVERSITY': 'washington-st',
  'WILLIAM & MARY': 'william-mary',
  'MANHATTAN UNIVERSITY': 'manhattan',
  'AUSTIN PEAY STATE UNIVERSITY': 'austin-peay',
  'CAMPBELL UNIVERSITY': 'campbell',
  'CHICAGO STATE UNIVERSITY': 'chicago-st',
  'JACKSONVILLE UNIVERSITY': 'jacksonville',
  'MERCYHURST UNIVERSITY': 'mercyhurst',
  'UNIVERSITY OF NEW ORLEANS': 'new-orleans',
  'UNIVERSITY OF RHODE ISLAND': 'rhode-island',
  'UTAH TECH UNIVERSITY': 'utah-tech',
  'UNIVERSITY OF WEST GEORGIA': 'west-georgia',
  'ST. BONAVENTURE UNIVERSITY': 'st-bonaventure',
  "LOUISIANA STATE UNIVERSITY AND AGRICULTURAL AND MECHANICAL COLLEGE (LSU)": 'lsu',
  "THE UNIVERSITY OF MISSISSIPPI (OLE MISS)": 'ole-miss',
  'BINGHAMTON UNIVERSITY, STATE UNIVERSITY OF NEW YORK': 'binghamton',
  'CALIFORNIA POLYTECHNIC STATE UNIVERSITY, SAN LUIS OBISPO': 'cal-poly',
  'EAST TEXAS A&M UNIVERSITY': 'east-texas-am',
  'INDIANA UNIVERSITY INDIANAPOLIS': 'iu-indy',
  'MARIST UNIVERSITY': 'marist',
  'NORTH CAROLINA AGRICULTURAL AND TECHNICAL STATE UNIVERSITY': 'nc-at',
  'SOUTHERN UTAH UNIVERSITY': 'southern-utah',
  'STONY BROOK UNIVERSITY, STATE UNIVERSITY OF NEW YORK': 'stony-brook',
  'THE UNIVERSITY OF ALABAMA AT BIRMINGHAM': 'uab',
  'THE UNIVERSITY OF TEXAS RIO GRANDE VALLEY': 'utrgv',
  'UNIVERSITY AT ALBANY, STATE UNIVERSITY OF NEW YORK': 'albany',
  'UNIVERSITY AT BUFFALO, THE STATE UNIVERSITY OF NEW YORK': 'buffalo',
  'UNIVERSITY OF MASSACHUSETTS LOWELL': 'umass-lowell',
};
